name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: connect ssh
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY_PRIV }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KEY_PUB }}" > ~/.ssh/id_ed25519.pub
          chmod 600 ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519.pub
          ssh-keyscan -H ${{ secrets.IP }} > ~/.ssh/known_hosts
          ls -l ~/.ssh/id_ed25519 ~/.ssh/id_ed25519.pub
      - name: run script
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SERVER }} "bash deploy.sh helloWorld"

      
