name: Revelar algo secrete
on: 
  push:
    branches: 
      - main 

jobs: 
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Revelar segredo
        env: 
          segredo: ${{ secrets.SEGREDO }}
        run: |
          echo "$segredo"
        
    
